siteTitle = "Stefan van Groningen"
url = "http://www.stefanvangroningen.com"
linkPrefix = "/notUsedYet"
email = "groninge@hotmail.com"
linkedin = "stefanvangroningen"
github = "groninge01"

[js]
head = """
if ('classList' in document.createElement('div') && 'querySelector' in document && 'addEventListener' in window && Array.prototype.forEach) {
  document.documentElement.classList += 'js';
  var script = document.createElement('script');
  script.src = '/bundle.js';
  document.getElementsByTagName('body')[0].appendChild(script);
}
"""
analytics = """
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-88166052-1', 'auto');
ga('send', 'pageview');
"""
font = """
var font = new FontFaceObserver('leagueSpartan-bold');
font.load().then(function () {
  document.documentElement.className += ' webfonts-loaded';
});
"""

favicons = '''
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png?v=1">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png?v=1">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png?v=1">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png?v=1">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png?v=1">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png?v=1">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png?v=1">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png?v=1">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png?v=1">
<link rel="icon" type="image/png" href="/favicon-32x32.png?v=1" sizes="32x32">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png?v=1" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-96x96.png?v=1" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png?v=1" sizes="16x16">
<link rel="manifest" href="/manifest.json?v=1">
<link rel="mask-icon" href="/safari-pinned-tab.svg?v=1" color="#1f262e">
<link rel="shortcut icon" href="/favicon.ico?v=1">
<meta name="apple-mobile-web-app-title" content="example.com">
<meta name="application-name" content="example.com">
<meta name="msapplication-TileColor" content="#603cba">
<meta name="msapplication-TileImage" content="/mstile-144x144.png?v=1">
<meta name="theme-color" content="#1f262e">
'''

[header]
text = '''
<p><b>Hi there!</b> Based in the city of Alkmaar, the Netherlands I am teaching myself to code: from front-end to back-end and everything in between.</p>
<p>I would love to help you to create a fast, secure and beautiful web experience for everyone!</p>
'''

[work]
title = "Work"
blurb = "Work blurb"
dir = "work"

[writing]
title = "Writing"
blurb = "Writing blurb"
dir = "writing"

[about]
title = "About"
text = '''
<div class="left@md mb-3 flex@sm items-center">
  <img src="/1avatar.jpg" srcset="/1avatar@2x.jpg 2x" width="150" height="150" alt="Profile picture of you" class="avatar block flexItem-25 w-25 mx-auto mb-3 mr-3@sm ml-0@sm mb-0@sm circle border borderColor-light" />
  <p class="flexItem-auto">I am following <a href="https://github.com/P1xt/p1xt-guides/blob/master/wd-cs.md" target="_blank">this guide</a> which is created by <a href="https://github.com/P1xt/p1xt-guides" target="_blank">P1xt</a>. I am currently on <i>Tier 1 - get started</i> reading the book <a href="https://github.com/getify/You-Dont-Know-JS/tree/master/async%20%26%20performance" target="_blank">"You Don't Know JS: Async & Performance"</a>. When taking a break from coding I am probably a) doing fun things with my family or b) getting stronger through calisthenics or c) just enjoying a craft beer while watching Twin Peaks.</p>
</div>
<div class="left@sm w-50@sm pr-2@sm mb-3 mb-0@sm">
  <h3 class="h4 mb-0">I Am Good With</h3>
  <ul style="margin-top:1.5rem">
    <li>HTML</li>
    <li>CSS</li>
    <li>JavaScript</li>
    <li>WordPress</li>
    <li>Linux</li>
    <li>nginx</li>
  </ul>
</div>
<div class="left@sm w-50@sm pl-2@sm">
  <h3 class="h4 mb-0">I Am Getting Better With</h3>
  <ul style="margin-top:1.5rem">
    <li>React</li>
    <li>JavaScript</li>
    <li>Math</li>
    <li>Git(Hub)</li>
    <li>Python</li>
  </ul>
</div>
'''
